# Generated by Django 4.1 on 2022-09-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventCardPropType',
        ),
        migrations.RenameField(
            model_name='iprogram',
            old_name='image',
            new_name='imagUrl',
        ),
        migrations.RemoveField(
            model_name='icategory',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='iprogram',
            name='idp',
        ),
        migrations.RemoveField(
            model_name='iprogram',
            name='imageUrl',
        ),
    ]
